source("renv/activate.R")

input_files <- list.files(
  "data-standardized/multi-agency",
  pattern = "_attributes\\.csv$",
  full.names = TRUE
)
input_csv <- tail(sort(input_files), 1)
output_csv <- "project-description-updates.csv"

if (length(input_files) == 0) {
  stop("No combined attribute CSV found.", call. = FALSE)
}

descriptions <- tibble::tribble(
  ~project_name, ~updated_description, ~sources,
  "McCormick-Williamson Tract (MWT) Monitoring Project (Phase B)", "Modify and lower selected McCormack-Williamson Tract levees, restore former agricultural land to subtidal, tidal marsh, and riparian habitats, and monitor performance, improving floodplain connectivity, aquatic and terrestrial habitat, and North Delta flood resilience.", "https://ceqanet.lci.ca.gov/2003012112/8",
  "Grizzly Slough Floodplain Restoration", "Breach the perimeter levee, realign and extend tidal channels, and add a low drainage berm at Grizzly Slough, restoring tidal and fluvial connections and creating additional floodplain and wetland habitat for native fish and wildlife.", "https://ceqanet.lci.ca.gov/2003012112/14",
  "Lower Elkhorn Basin Levee Setback", "Set back approximately seven miles of levees, remove portions of the existing levee system, and modify related flood facilities to widen the Yolo and Sacramento Bypasses, increasing flood conveyance and public safety while expanding inundated floodplain and riparian habitat.", "https://water.ca.gov/Programs/Flood-Management/Flood-Projects/Lower-Elkhorn-Basin",
  "Kopta Slough Multi-Benefit Project", "Remove rock revetment, recontour the riverbank, and convert agricultural land to native riparian and floodplain habitat along Kopta Slough, improving fish and wildlife habitat, river function, public recreation, and flood-management efficiency.", "https://water.ca.gov/PROGRAMS/ALL-PROGRAMS/ECORESTORE",
  "Dos Rios Norte", "Improve hydrologic connections between the Feather River, Sacramento River, and adjacent floodplain areas to create and enhance seasonal floodplain habitat that supports Chinook salmon and steelhead rearing.", "https://water.ca.gov/News/News-Releases/2024/Oct-24/California-Makes-Progress-to-Ensure-Healthy-Rivers-and-Landscapes",
  "Tisdale Weir Reoperation", "Rehabilitate Tisdale Weir and install an operable fish-passage facility connecting the weir notch to the Sacramento River, addressing structural deficiencies while reducing fish stranding and improving upstream passage for salmon, sturgeon, and other native fish.", "https://ceqanet.lci.ca.gov/2019049093/2",
  "Agricultural Road Crossing #4 Improvements", "Remove the existing earthen Agricultural Road Crossing #4 and replace it with a bridge spanning Tule Canal, restoring unimpeded fish movement while retaining agricultural and vehicle access during non-flood conditions.", "https://ceqanet.lci.ca.gov/2021070310",
  "Prospect Island Tidal Habitat Restoration Project", "Restore tidal processes on Prospect Island by grading interior areas, managing vegetation, constructing channels and topographic features, and breaching exterior levees, converting about 1,600 acres to tidal habitat that supports Delta fish, improves food-web productivity, water quality, carbon sequestration, and climate resilience.", "https://water.ca.gov/Programs/Integrated-Science-and-Engineering/Restoration-Mitigation-Compliance/Delta-Projects; https://water.ca.gov/News/News-Releases/2024/Nov-24/Reclamation-DWR-Celebrate-Launch-of-Key-Delta-Habitat-Restoration-Project",
  "Little Egbert Multi-Benefit Project", "Transform the Little Egbert Tract near Rio Vista into flood-conveyance and habitat zones by modifying levees and infrastructure, creating inflow and outflow connections, constructing subtidal swales and habitat berms, and restoring native riparian, tidal, subtidal, and floodplain vegetation to improve flood protection, native-fish habitat, and recreation.", "https://water.ca.gov/Programs/All-Programs/Multibenefit/Little-Egbert",
  "Tide's End Multibenefit Restoration Project", "Restore and enhance roughly 2,200 acres at the downstream end of the Yolo Bypass by creating connected tidal marsh, floodplain, wetland, and riparian habitat while retaining compatible wildlife-friendly agriculture and managed wetlands, improving habitat connectivity, flood capacity, drainage, and irrigation.", "https://water.ca.gov/Programs/All-Programs/Multibenefit/Tides-End-Multibenefit-Restoration-Project",
  "Dutch Slough Tidal Restoration Project (Phase 2)", "Convert former grazing and dairy land near Oakley to tidal marsh by grading the remaining project parcel, restoring native vegetation, and breaching levees to reestablish daily tidal exchange, expanding habitat for native Delta fish and wildlife while improving flood protection, public access, education, and recreation.", "https://water.ca.gov/Programs/Integrated-Regional-Water-Management/Delta-Ecosystem-Enhancement-Program/Dutch-Slough-Tidal-Restoration-Project",
  "Feather River Salmonid Spawning Habitat Improvement - 2024", "Place, sort, and harvest appropriately sized gravel and cobble in the Feather River to rebuild spawning substrate, increasing the quantity and quality of accessible spawning habitat for Chinook salmon and steelhead.", "https://water.ca.gov/News/News-Releases/2024/Oct-24/California-Makes-Progress-to-Ensure-Healthy-Rivers-and-Landscapes",
  "P68 Feather River Salmon Habitat Improvement Project", "Place and distribute spawning-sized gravel at targeted Feather River locations to expand accessible spawning habitat for salmonids, building on the first-phase gravel additions and supporting continued Chinook salmon and steelhead reproduction.", "https://water.ca.gov/News/News-Releases/2024/Oct-24/California-Makes-Progress-to-Ensure-Healthy-Rivers-and-Landscapes",
  "Mokelumne River - MRDUA Large Floodplain Project", "Reconnect and lower floodplain surfaces in the Mokelumne River Day Use Area to create seasonally inundated habitat, increasing rearing opportunities for juvenile Chinook salmon and restoring floodplain function.", "https://www.ebmud.com/recreation/protecting-natural-habitat/lower-mokelumne-river-spawning-and-rearing-habitat-improvement-project",
  "Mokelumne River - Gravel Maintenance Project - Early Implementation Projects", "Maintain spawning gravel at suitable elevations in the Lower Mokelumne River through targeted gravel replenishment and management, sustaining accessible spawning habitat for Chinook salmon and steelhead where dams and historic mining have reduced natural gravel supply.", "https://www.ebmud.com/recreation/protecting-natural-habitat/lower-mokelumne-river-spawning-and-rearing-habitat-improvement-project",
  "Mokelumne River - Floodplain Restoration Projects - Early Implementation Projects", "Restore and reconnect floodplain areas in the Mokelumne River Day Use Area to provide seasonal inundation and shallow-water rearing habitat for juvenile Chinook salmon while improving floodplain processes.", "https://www.ebmud.com/recreation/protecting-natural-habitat/lower-mokelumne-river-spawning-and-rearing-habitat-improvement-project",
  "Mokelumne River - CE Large Floodplain Restoration Project", "Reconnect and restore a larger Mokelumne River floodplain area to provide seasonally inundated juvenile salmon rearing habitat and improve floodplain function.", "https://www.ebmud.com/recreation/protecting-natural-habitat/lower-mokelumne-river-spawning-and-rearing-habitat-improvement-project",
  "Mokelumne River - In Channel Rearing Habitat Restoration Project", "Implement in-channel habitat improvements on the Lower Mokelumne River to create shallow, hydraulically diverse rearing conditions for juvenile Chinook salmon and improve the ecological function of the regulated river reach.", "https://www.ebmud.com/recreation/protecting-natural-habitat/lower-mokelumne-river-spawning-and-rearing-habitat-improvement-project",
  "Mokelumne River - Gravel Maintenance Project – Current and Future Maintenance Projects", "Continue targeted maintenance of Lower Mokelumne River spawning gravel so suitable substrate remains available for Chinook salmon and steelhead despite limited natural gravel recruitment below upstream dams.", "https://www.ebmud.com/recreation/protecting-natural-habitat/lower-mokelumne-river-spawning-and-rearing-habitat-improvement-project",
  "Oroville Wildlife Area River Restoration Project at Robinson's Riffle", "Excavate relict mine tailings, construct gravel bars and riffles, reconnect the Feather River to its historic floodplain, and create seasonal side-channel, pool, and riparian features at Robinson's Riffle, improving Chinook salmon and steelhead spawning and rearing habitat while reducing flood stages and supporting recreation.", "https://ceqanet.lci.ca.gov/2019100230/65; https://storymaps.arcgis.com/stories/bfb698fb4f6f405b857107aa4f5aadd1",
  "Nishikawa on Putah Creek", "Restore approximately one-half mile of Putah Creek by narrowing and meandering the low-flow channel and lowering the floodplain, increasing the extent and frequency of inundation to improve juvenile Chinook salmon rearing habitat and habitat for other native fish.", "https://scwa2.com/wp-content/uploads/2026/02/FEB.2026.BOD_.FULLPACKET-ID-360706.pdf; https://scwa2.com/about-us/environmental-permit-compliance-documents/",
  "Putah Gravel Augmentation and Scarification", "Periodically add and scarify gravel in Putah Creek to maintain clean, suitably sized spawning substrate, improving Chinook salmon spawning habitat in a reach with limited natural sediment replenishment.", "https://scwa2.com/about-us/environmental-permit-compliance-documents/",
  "Putah Creek fish passage at Los Rios Check Dam", "Advance planning, design, environmental review, and permitting for fish-passage improvements at Los Rios Check Dam so Chinook salmon can move more freely through Putah Creek and reach upstream habitat.", "https://scwa2.com/about-us/environmental-permit-compliance-documents/",
  "Putah Creek fish passage at County Rd 106a", "Advance planning, design, environmental review, and permitting for fish-passage improvements at the County Road 106A crossing, reducing an obstruction to Chinook salmon movement and improving access to habitat in Putah Creek.", "https://scwa2.com/about-us/environmental-permit-compliance-documents/",
  "Upstream of Old LaGrange Bridge Restoration Project", "Restore about one mile of the Tuolumne River upstream of Old La Grange Bridge by reconstructing and contouring riffles, placing coarse sediment and spawning gravel, and reconnecting adjacent floodplain surfaces, increasing channel complexity and spawning and rearing habitat for Chinook salmon and steelhead.", "https://ceqanet.lci.ca.gov/2023110570; https://www.tid.org/tuolumne-river-partners-complete-habitat-restoration-project/",
  "Powerhouse Riffles Restoration Project", "Rebuild approximately 2,500 feet of Lower Tuolumne River habitat below La Grange Dam by adding clean gravel and constructing riffles, gravel bars, habitat boulders, and large-wood features, replacing simplified cascades and pools with more complex spawning and rearing habitat for salmonids.", "https://www.waterboards.ca.gov/centralvalley/board_decisions/adopted_orders/401_wqcerts/5b50cr00132.pdf",
  "Nimbus Basin", "Restore spawning and juvenile rearing habitat in the Lower American River at Nimbus Basin by replenishing and sorting clean gravel, carving and enhancing side channels, adding large wood, and establishing riparian vegetation to provide suitable spawning substrate, cover, shade, and food-web habitat for Chinook salmon and steelhead.", "https://waterforum.org/habitat2022/",
  "Upper Sailor Bar", "Restore spawning and juvenile rearing habitat at Upper Sailor Bar by replenishing and sorting clean gravel and enhancing side-channel and floodplain features, increasing suitable substrate, cover, and shallow-water habitat for Chinook salmon and steelhead.", "https://www.waterforum.org/wp-content/uploads/2019/06/LAR-Anadromous-Fish-Habitat-Restoration-Project_Environmental-Assessment-Initial-Study_June-2019.pdf; https://waterforum.org/habitat-enhancement/",
  "Lower Sailor Bar", "Restore spawning and juvenile rearing habitat at Lower Sailor Bar by replenishing and sorting clean gravel, carving and enhancing side channels, adding large wood, and establishing riparian vegetation to provide spawning substrate, cover, shade, and food-web habitat for Chinook salmon and steelhead.", "https://waterforum.org/habitat2022/",
  "Ancil Hoffman", "Restore spawning and juvenile rearing habitat at Ancil Hoffman Park by replenishing and sorting clean gravel and enhancing side-channel and floodplain features, increasing suitable substrate and protected shallow-water habitat for Chinook salmon and steelhead.", "https://www.waterforum.org/wp-content/uploads/2019/06/LAR-Anadromous-Fish-Habitat-Restoration-Project_Environmental-Assessment-Initial-Study_June-2019.pdf; https://waterforum.org/habitat-enhancement/",
  "Upper River Bend, Phase 1", "Restore spawning and juvenile rearing habitat at Upper River Bend by replenishing and sorting clean gravel and enhancing side-channel and floodplain features, improving suitable substrate and protected shallow-water habitat for Chinook salmon and steelhead.", "https://www.waterforum.org/wp-content/uploads/2019/06/LAR-Anadromous-Fish-Habitat-Restoration-Project_Environmental-Assessment-Initial-Study_June-2019.pdf; https://waterforum.org/habitat-enhancement/",
  "River Bend", "Restore spawning and juvenile rearing habitat at River Bend by replenishing and sorting clean gravel and enhancing side-channel and floodplain features, improving suitable substrate and protected shallow-water habitat for Chinook salmon and steelhead.", "https://www.waterforum.org/wp-content/uploads/2019/06/LAR-Anadromous-Fish-Habitat-Restoration-Project_Environmental-Assessment-Initial-Study_June-2019.pdf; https://waterforum.org/habitat-enhancement/",
  "Hallwood Side Channel and Floodplain Restoration Project", "Create and enhance frequently inundated floodplain, side-channel, and other off-channel habitat along the lower Yuba River, increasing protected seasonal rearing habitat for Chinook salmon and steelhead while reducing local flood-stage elevations and velocities.", "https://www.yubawater.org/CivicAlerts.asp?AID=229",
  "Lower Long Bar Habitat Enhancement Project", "Lower and contour floodplain surfaces at Lower Long Bar to increase seasonal inundation and create rearing habitat for juvenile Chinook salmon and steelhead, improving floodplain connectivity and habitat diversity along the lower Yuba River.", "https://www.yubawater.org/CivicAlerts.asp?AID=229",
  "Upper Long Bar Habitat Enhancement Project", "Lower and contour floodplain surfaces at Upper Long Bar to increase seasonal inundation and create rearing habitat for juvenile Chinook salmon and steelhead, improving floodplain connectivity and habitat diversity along the lower Yuba River.", "https://www.yubawater.org/CivicAlerts.asp?AID=229",
  "Upper Rose Bar Habitat Enhancement Project", "Place spawning-sized gravel to construct two riffles, excavate a side-channel floodplain area, and create a lateral rearing feature at Upper Rose Bar, expanding Chinook salmon and steelhead spawning and juvenile rearing habitat.", "https://www.yubawater.org/CivicAlerts.asp?AID=229"
)

ceqa_references <- tibble::tribble(
  ~project_name, ~ceqa_sources, ~ceqa_note,
  "McCormick-Williamson Tract (MWT) Monitoring Project (Phase B)", "https://ceqanet.lci.ca.gov/2003012112/8", "Supplemental EIR; description revised to reflect levee and habitat actions.",
  "Grizzly Slough Floodplain Restoration", "https://ceqanet.lci.ca.gov/2003012112/14", "Notice of Determination for a project amendment.",
  "Lower Elkhorn Basin Levee Setback", "https://ceqanet.lci.ca.gov/2016092015/5", "Notice of Determination; includes levee setback, floodplain expansion, and habitat actions.",
  "Kopta Slough Multi-Benefit Project", "https://ceqanet.lci.ca.gov/2022120577", "Mitigated Negative Declaration.",
  "Tisdale Weir Reoperation", "https://ceqanet.lci.ca.gov/2019049093/2", "Draft EIR; source documents identify this as a weir rehabilitation and fish-passage project.",
  "Agricultural Road Crossing #4 Improvements", "https://ceqanet.lci.ca.gov/2021070310", "Notice of Exemption; description corrected to bridge replacement rather than fish-screen installation.",
  "Prospect Island Tidal Habitat Restoration Project", "https://ceqanet.lci.ca.gov/2013052056/3", "Environmental Impact Report.",
  "Little Egbert Multi-Benefit Project", "https://ceqanet.lci.ca.gov/2023060369", "Notice of Preparation for an EIR.",
  "Tide's End Multibenefit Restoration Project", "https://ceqanet.lci.ca.gov/2024070944/2", "Supplemental EIR.",
  "Dutch Slough Tidal Restoration Project (Phase 2)", "https://ceqanet.lci.ca.gov/2006042009/9", "Environmental document for Dutch Slough tidal restoration.",
  "Oroville Wildlife Area River Restoration Project at Robinson's Riffle", "https://ceqanet.lci.ca.gov/2019100230/65", "Notice of Determination; description revised using its channel, floodplain, and riparian restoration components.",
  "Nishikawa on Putah Creek", "https://scwa2.com/about-us/environmental-permit-compliance-documents/", "Agency CEQA document portal for the Lower Putah Creek Restoration Project, Nishikawa Reach.",
  "Upstream of Old LaGrange Bridge Restoration Project", "https://ceqanet.lci.ca.gov/2023110570", "Notice of Exemption for a statutory fish-and-wildlife restoration project.",
  "Powerhouse Riffles Restoration Project", "https://wildlife.ca.gov/Conservation/Cutting-Green-Tape/SERP/Concurrences/powerhouse-riffles-restoration-project", "CDFW concurrence under the statutory CEQA exemption for restoration projects.",
  "Mokelumne River - MRDUA Large Floodplain Project", "https://www.ebmud.com/download_file/force/1093/567?lower_mokelumne_river_spawning_and_rearing_habitat_improvement_project.pdf=", "EBMUD environmental review document for the Lower Mokelumne spawning and rearing habitat program.",
  "Mokelumne River - Gravel Maintenance Project - Early Implementation Projects", "https://www.ebmud.com/download_file/force/1093/567?lower_mokelumne_river_spawning_and_rearing_habitat_improvement_project.pdf=", "EBMUD environmental review document for the Lower Mokelumne spawning and rearing habitat program.",
  "Mokelumne River - Floodplain Restoration Projects - Early Implementation Projects", "https://www.ebmud.com/download_file/force/1093/567?lower_mokelumne_river_spawning_and_rearing_habitat_improvement_project.pdf=", "EBMUD environmental review document for the Lower Mokelumne spawning and rearing habitat program.",
  "Mokelumne River - CE Large Floodplain Restoration Project", "https://www.ebmud.com/download_file/force/1093/567?lower_mokelumne_river_spawning_and_rearing_habitat_improvement_project.pdf=", "EBMUD environmental review document for the Lower Mokelumne spawning and rearing habitat program.",
  "Mokelumne River - In Channel Rearing Habitat Restoration Project", "https://www.ebmud.com/download_file/force/1093/567?lower_mokelumne_river_spawning_and_rearing_habitat_improvement_project.pdf=", "EBMUD environmental review document for the Lower Mokelumne spawning and rearing habitat program.",
  "Mokelumne River - Gravel Maintenance Project – Current and Future Maintenance Projects", "https://www.ebmud.com/download_file/force/1093/567?lower_mokelumne_river_spawning_and_rearing_habitat_improvement_project.pdf=", "EBMUD environmental review document for the Lower Mokelumne spawning and rearing habitat program.",
  "Nimbus Basin", "https://www.waterforum.org/wp-content/uploads/2019/06/LAR-Anadromous-Fish-Habitat-Restoration-Project_Environmental-Assessment-Initial-Study_June-2019.pdf", "Environmental Assessment/Initial Study for the Lower American River habitat restoration program.",
  "Upper Sailor Bar", "https://www.waterforum.org/wp-content/uploads/2019/06/LAR-Anadromous-Fish-Habitat-Restoration-Project_Environmental-Assessment-Initial-Study_June-2019.pdf", "Environmental Assessment/Initial Study for the Lower American River habitat restoration program.",
  "Lower Sailor Bar", "https://www.waterforum.org/wp-content/uploads/2019/06/LAR-Anadromous-Fish-Habitat-Restoration-Project_Environmental-Assessment-Initial-Study_June-2019.pdf", "Environmental Assessment/Initial Study for the Lower American River habitat restoration program.",
  "Ancil Hoffman", "https://www.waterforum.org/wp-content/uploads/2019/06/LAR-Anadromous-Fish-Habitat-Restoration-Project_Environmental-Assessment-Initial-Study_June-2019.pdf", "Environmental Assessment/Initial Study for the Lower American River habitat restoration program.",
  "Upper River Bend, Phase 1", "https://www.waterforum.org/wp-content/uploads/2019/06/LAR-Anadromous-Fish-Habitat-Restoration-Project_Environmental-Assessment-Initial-Study_June-2019.pdf", "Environmental Assessment/Initial Study for the Lower American River habitat restoration program.",
  "River Bend", "https://www.waterforum.org/wp-content/uploads/2019/06/LAR-Anadromous-Fish-Habitat-Restoration-Project_Environmental-Assessment-Initial-Study_June-2019.pdf", "Environmental Assessment/Initial Study for the Lower American River habitat restoration program."
)

projects <- readr::read_csv(input_csv, show_col_types = FALSE) |>
  dplyr::select(project_name, original_description = project_description)

missing_descriptions <- dplyr::anti_join(projects, descriptions, by = "project_name")
unexpected_descriptions <- dplyr::anti_join(descriptions, projects, by = "project_name")
if (nrow(missing_descriptions) > 0 || nrow(unexpected_descriptions) > 0) {
  stop("Project-description entries must match the combined project list exactly.", call. = FALSE)
}

review <- projects |>
  dplyr::left_join(descriptions, by = "project_name") |>
  dplyr::left_join(ceqa_references, by = "project_name") |>
  dplyr::mutate(
    ceqa_note = dplyr::coalesce(
      ceqa_note,
      "No project-specific CEQA record was located during this review; description remains conservative and is supported by the listed project source."
    )
  ) |>
  dplyr::arrange(project_name)

readr::write_csv(review, output_csv, na = "")
message("Wrote ", output_csv)
